/**
 * LaTeX Document Formatting Engine
 * Synthesizes publication-grade, Overleaf-ready LaTeX documents
 * with modern typography, theorem environments, and clean layout packages.
 */

export interface LatexSection {
  title: string;
  content: string;
  equations?: string[];
  subsections?: { title: string; content: string }[];
}

export interface LatexDocumentOptions {
  docType: "article" | "ieee_conference" | "beamer_slides" | "exam_viva_report" | "cheat_sheet";
  title: string;
  authors: { name: string; affiliation?: string; email?: string }[];
  abstract?: string;
  sections: LatexSection[];
  keywords?: string[];
  bibEntries?: string[];
}

export function generateLatexDocument(opts: LatexDocumentOptions): string {
  if (opts.docType === "beamer_slides") {
    return generateBeamerSlides(opts);
  }
  if (opts.docType === "cheat_sheet") {
    return generateCheatSheet(opts);
  }

  const isIeee = opts.docType === "ieee_conference";
  const docClass = isIeee ? "\\documentclass[conference,10pt]{IEEEtran}" : "\\documentclass[11pt,a4paper]{article}";

  const code: string[] = [];
  code.push(docClass);
  code.push("% Generated by ScholarTex MCP — Academic Mathematical Proof Engine");
  code.push("\\usepackage[utf8]{inputenc}");
  code.push("\\usepackage[T1]{fontenc}");
  code.push("\\usepackage{amsmath,amssymb,amsfonts,amsthm}");
  code.push("\\usepackage{bm}");
  code.push("\\usepackage{booktabs}");
  code.push("\\usepackage{microtype}");
  code.push("\\usepackage{graphicx}");
  code.push("\\usepackage{tikz}");
  code.push("\\usepackage{hyperref}");
  code.push("\\hypersetup{colorlinks=true, linkcolor=blue!70!black, citecolor=teal!70!black, urlcolor=purple!70!black}");

  if (!isIeee) {
    code.push("\\usepackage[margin=1in]{geometry}");
    code.push("\\usepackage{parskip}");
  }

  // Theorem Environments
  code.push("% --- Mathematical Environments ---");
  code.push("\\newtheorem{theorem}{Theorem}[section]");
  code.push("\\newtheorem{lemma}[theorem]{Lemma}");
  code.push("\\newtheorem{definition}{Definition}[section]");
  code.push("\\newtheorem{corollary}[theorem]{Corollary}");
  code.push("\\newtheorem{remark}{Remark}");

  // Metadata
  code.push(`\\title{\\textbf{${opts.title}}}`);
  if (isIeee) {
    const authorBlocks = opts.authors.map(a =>
      `\\IEEEauthorblockN{${a.name}}\n\\IEEEauthorblockA{${a.affiliation || "Dept. of AI & Machine Learning"}\\\\${a.email || ""}}`
    ).join("\n\\and\n");
    code.push(`\\author{${authorBlocks}}`);
  } else {
    const authorStr = opts.authors.map(a => `${a.name}${a.affiliation ? `\\\\ \\small ${a.affiliation}` : ""}`).join(" \\and ");
    code.push(`\\author{${authorStr}}`);
    code.push("\\date{\\today}");
  }

  code.push("\\begin{document}");
  code.push("\\maketitle");

  // Abstract
  if (opts.abstract) {
    code.push("\\begin{abstract}");
    code.push(opts.abstract);
    if (opts.keywords && opts.keywords.length > 0) {
      code.push(`\n\\vspace{0.5em}\\noindent\\textbf{Keywords---} ${opts.keywords.join(", ")}`);
    }
    code.push("\\end{abstract}\n");
  }

  // Sections
  opts.sections.forEach(sec => {
    code.push(`\\section{${sec.title}}`);
    code.push(sec.content);

    if (sec.equations && sec.equations.length > 0) {
      code.push("\\begin{align}");
      code.push(sec.equations.join(" \\\\\n"));
      code.push("\\end{align}");
    }

    if (sec.subsections) {
      sec.subsections.forEach(sub => {
        code.push(`\\subsection{${sub.title}}`);
        code.push(sub.content);
      });
    }
    code.push("");
  });

  // Bibliography
  if (opts.bibEntries && opts.bibEntries.length > 0) {
    code.push("\\begin{thebibliography}{99}");
    opts.bibEntries.forEach((bib, i) => {
      code.push(`\\bibitem{ref${i + 1}} ${bib}`);
    });
    code.push("\\end{thebibliography}");
  }

  code.push("\\end{document}");
  return code.join("\n");
}

function generateBeamerSlides(opts: LatexDocumentOptions): string {
  const code: string[] = [];
  code.push("\\documentclass[aspectratio=169,10pt]{beamer}");
  code.push("\\usetheme{Metropolis} % Clean, modern academic theme");
  code.push("\\usepackage{amsmath,amssymb,bm,booktabs}");
  code.push(`\\title{${opts.title}}`);
  code.push(`\\author{${opts.authors.map(a => a.name).join(", ")}}`);
  code.push(`\\institute{${opts.authors[0]?.affiliation || "Walchand College of Engineering"}}`);
  code.push("\\date{\\today}");

  code.push("\\begin{document}");
  code.push("\\frame{\\titlepage}");

  opts.sections.forEach(sec => {
    code.push(`\\begin{frame}{${sec.title}}`);
    code.push(sec.content);
    if (sec.equations && sec.equations.length > 0) {
      code.push("\\begin{align*}");
      code.push(sec.equations.join(" \\\\\n"));
      code.push("\\end{align*}");
    }
    code.push("\\end{frame}\n");
  });

  code.push("\\end{document}");
  return code.join("\n");
}

function generateCheatSheet(opts: LatexDocumentOptions): string {
  const code: string[] = [];
  code.push("\\documentclass[10pt,landscape]{article}");
  code.push("\\usepackage[margin=0.4in]{geometry}");
  code.push("\\usepackage{multicol,amsmath,amssymb,bm,booktabs,xcolor}");
  code.push("\\pagestyle{empty}");
  code.push("\\begin{document}");
  code.push(`\\begin{center}\\textbf{\\Large ${opts.title}} -- \\textit{Academic Quick Reference}\\end{center}`);
  code.push("\\begin{multicols*}{3}");

  opts.sections.forEach(sec => {
    code.push(`\\noindent\\textbf{\\color{blue!80!black} $\\blacksquare$ ${sec.title}}\\\\`);
    code.push(sec.content);
    if (sec.equations && sec.equations.length > 0) {
      code.push("\\begin{align*}");
      code.push(sec.equations.join(" \\\\\n"));
      code.push("\\end{align*}");
    }
    code.push("\\vspace{0.8em}");
  });

  code.push("\\end{multicols*}");
  code.push("\\end{document}");
  return code.join("\n");
}
